### ISSUE TITLE
Aria2连接出错，请检查url和token

### ISSUE THREAD

**Issue by nep1406886** [xuanpro/ariabot#2]
token直接复制的应该没错，RPC地址ws://127.0.0.1:6800/jsonrpc，alist上同token和地址连接无问题

log
![image](https://github.com/xuanpro/ariabot/assets/67021805/5a0a96dc-3355-4f8e-9b99-d8fcca55ef72)

**Comment by xuanpro** [comment]
IP地址填错了，不可能是127.0.0.1
填aria2宿主机IP

**Comment by nep1406886** [comment]
> IP地址填错了，不可能是127.0.0.1 填aria2宿主机IP

下载机就是本机的情况下也需要填本机IP吗？

**Comment by xuanpro** [comment]
127.0.0.1在bot里边指的是bot自身

**Comment by nep1406886** [comment]
> 127.0.0.1在bot里边指的是bot自身

好的，也就是说只能填服务器IP是把，感谢回复
